package com.kisanprocure.service;
import com.kisanprocure.dto.booking.BookingDtos.*; import com.kisanprocure.entity.*; import com.kisanprocure.entity.enums.*; import com.kisanprocure.exception.ApiException; import com.kisanprocure.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class BookingService {
 private final BookingRepository bookings; private final FarmerRepository farmers; private final CentreRepository centres; private final CropRepository crops; private final SlotRepository slots; private final QueueEntryRepository queue;
 @Transactional public CreateBookingResponse create(Long userId,CreateBookingRequest r){Farmer f=farmers.findByUserId(userId).orElseThrow(()->new ApiException(404,"Farmer profile not found")); Centre c=centres.findById(r.centreId()).orElseThrow(()->new ApiException(404,"Centre not found")); Crop crop=crops.findById(r.cropId()).orElseThrow(()->new ApiException(404,"Crop not found")); Slot s=slots.findByIdAndCentreId(r.slotId(),r.centreId()).orElseThrow(()->new ApiException(404,"Slot not found")); double avail=s.getCapacity()-s.getBookedCapacity(); if(avail+1e-9<r.quantity()) throw new ApiException(409,"Insufficient slot capacity"); s.setBookedCapacity(s.getBookedCapacity()+r.quantity()); slots.save(s); int token=bookings.findByCentreIdAndSlotSlotDateOrderByTokenNumber(c.getId(),s.getSlotDate()).size()+1; String bid="KP-"+s.getSlotDate().toString().replace("-","")+"-"+String.format("%04d",token); Booking b=bookings.save(Booking.builder().bookingId(bid).farmer(f).centre(c).crop(crop).slot(s).expectedQuantity(r.quantity()).tokenNumber(token).status(BookingStatus.BOOKED).createdAt(OffsetDateTime.now()).build()); return new CreateBookingResponse(true,"Booking confirmed",summary(b)); }
 public Booking get(Long id){return bookings.findById(id).orElseThrow(()->new ApiException(404,"Booking not found"));}
public BookingSummary summary(Booking b){return new BookingSummary(b.getId(),b.getBookingId(),String.valueOf(b.getTokenNumber()),b.getCentre().getId(),b.getCrop().getName(),b.getExpectedQuantity(),b.getSlot().getStartTime()+"-"+b.getSlot().getEndTime(),b.getStatus().name());}
 @Transactional public void cancel(Long id,String reason){Booking b=get(id); if(b.getStatus()==BookingStatus.COMPLETED) throw new ApiException(409,"Completed booking cannot be cancelled"); b.setStatus(BookingStatus.CANCELLED); Slot s=b.getSlot(); s.setBookedCapacity(Math.max(0,s.getBookedCapacity()-b.getExpectedQuantity())); slots.save(s); bookings.save(b);}
 @Transactional public void checkIn(Long id){Booking b=get(id); if(b.getStatus()!=BookingStatus.BOOKED) throw new ApiException(409,"Booking is not in BOOKED state"); int pos=queue.findByCentreIdAndBookingSlotSlotDateAndStatusInOrderByQueuePosition(b.getCentre().getId(),b.getSlot().getSlotDate(),List.of(QueueStatus.WAITING,QueueStatus.SERVING)).size()+1; b.setStatus(BookingStatus.WAITING); bookings.save(b); queue.save(QueueEntry.builder().booking(b).centre(b.getCentre()).queuePosition(pos).estimatedWait(0).status(QueueStatus.WAITING).checkedInAt(OffsetDateTime.now()).build()); }
}
