package com.kisanprocure.service;
import com.kisanprocure.dto.centre.CentreDtos.*; import com.kisanprocure.entity.*; import com.kisanprocure.exception.ApiException; import com.kisanprocure.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import java.util.*; import java.time.*;
@Service @RequiredArgsConstructor public class CentreService {
 private final CentreRepository centres; private final CentreCropRepository centreCrops; private final CropRepository crops; private final SlotRepository slots;
 public List<NearbyCentreResponse> nearby(double lat,double lng,double radius,Long cropId){return centres.findNearby(lat,lng,radius).stream().filter(c->cropId==null||centreCrops.findByCentreIdAndCropId(c.getId(),cropId).map(CentreCrop::getIsAvailable).orElse(false)).map(c->new NearbyCentreResponse(c.getId(),c.getName(),distance(lat,lng,c.getLatitude(),c.getLongitude()),0,0,c.getLatitude(),c.getLongitude(),c.getStatus().name())).toList();}
 public CapacityResponse capacity(Long id){Centre c=get(id); double reserved=slots.findByCentreIdAndSlotDateOrderByStartTime(id,LocalDate.now()).stream().mapToDouble(Slot::getBookedCapacity).sum(); return new CapacityResponse(id,c.getDailyCapacity(),reserved,Math.max(0,c.getDailyCapacity()-reserved));}
 public CentreDetailsResponse details(Long id,double userLat,double userLng){Centre c=get(id); List<CropInfo> list=centreCrops.findByCentreId(id).stream().map(x->new CropInfo(x.getCrop().getId(),x.getCrop().getName(),x.getCrop().getUnit(),x.getRate(),x.getIsAvailable())).toList(); return new CentreDetailsResponse(c.getId(),c.getName(),c.getCode(),c.getAddress(),c.getLatitude(),c.getLongitude(),c.getDailyCapacity(),c.getStatus().name(),distance(userLat,userLng,c.getLatitude(),c.getLongitude()),list,List.of("weighbridge","storage","drinking_water","waiting_area"));}
 public SlotsResponse slots(Long centreId,LocalDate date,Long cropId,double qty){get(centreId); List<SlotResponse> out=slots.findByCentreIdAndSlotDateOrderByStartTime(centreId,date).stream().map(s->{double a=Math.max(0,s.getCapacity()-s.getBookedCapacity()); String st=a>=qty?"AVAILABLE":"INSUFFICIENT_CAPACITY";return new SlotResponse(s.getId(),s.getStartTime().toString(),s.getEndTime().toString(),s.getCapacity(),s.getBookedCapacity(),a,st);}).toList(); return new SlotsResponse(centreId,date.toString(),out);}
 public Centre get(Long id){return centres.findById(id).orElseThrow(()->new ApiException(404,"Centre not found"));}
 public static double distance(double a,double b,double c,double d){double R=6371,la=Math.toRadians(a),lc=Math.toRadians(c),dl=Math.toRadians(c-a),do1=Math.toRadians(d-b); double x=Math.sin(dl/2)*Math.sin(dl/2)+Math.cos(la)*Math.cos(lc)*Math.sin(do1/2)*Math.sin(do1/2); return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
}
