package com.kisanprocure.service;
import com.kisanprocure.dto.officer.OfficerDtos.*; import com.kisanprocure.entity.*; import com.kisanprocure.entity.enums.*; import com.kisanprocure.exception.ApiException; import com.kisanprocure.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class ProcurementService {
 private final BookingRepository bookings; private final QualityCheckRepository qualities; private final WeighmentRepository weighments; private final ProcurementRepository procurements; private final QueueEntryRepository queue;
 @Transactional public void quality(Long id, QualityCheckRequest r){Booking b=bookings.findById(id).orElseThrow(()->new ApiException(404,"Booking not found")); if(b.getStatus()==BookingStatus.CANCELLED) throw new ApiException(409,"Cancelled booking"); qualities.save(QualityCheck.builder().booking(b).moisture(r.moisture()).foreignMatter(r.foreignMatter()).qualityGrade(r.qualityGrade()).status(QualityStatus.valueOf(r.status())).remarks(r.remarks()).build()); b.setStatus(QualityStatus.valueOf(r.status())==QualityStatus.PASSED?BookingStatus.WEIGHMENT:BookingStatus.QUALITY_CHECK); bookings.save(b); }
 @Transactional public void weighment(Long id, WeighmentRequest r){Booking b=bookings.findById(id).orElseThrow(()->new ApiException(404,"Booking not found")); weighments.save(Weighment.builder().booking(b).expectedQuantity(r.expectedQuantity()).actualQuantity(r.actualQuantity()).build()); b.setStatus(BookingStatus.PROCUREMENT); bookings.save(b); }
 @Transactional public Procurement procurement(Long id, ProcurementRequest r){Booking b=bookings.findById(id).orElseThrow(()->new ApiException(404,"Booking not found")); Procurement p=procurements.save(Procurement.builder().booking(b).quantity(r.quantity()).rate(r.rate()).totalAmount(r.quantity()*r.rate()).status(ProcurementStatus.COMPLETED).build()); b.setStatus(BookingStatus.COMPLETED); bookings.save(b); queue.findByBookingId(id).ifPresent(q->{q.setStatus(QueueStatus.COMPLETED);queue.save(q);}); return p; }
 @Transactional public void updateStatus(Long id,String status){Booking b=bookings.findById(id).orElseThrow(()->new ApiException(404,"Booking not found")); b.setStatus(BookingStatus.valueOf(status)); bookings.save(b);}
}
